# Generated by Django 4.1.4 on 2022-12-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reciever",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reciever",
                to="banking.customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sender",
                to="banking.customer",
            ),
        ),
    ]
