# Generated by Django 4.1.4 on 2022-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_alter_transaction_reciever_alter_transaction_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="overdraft",
            field=models.IntegerField(default=0),
        ),
    ]
