# Generated by Django 4.1.5 on 2023-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="date",
            field=models.DateField(editable=False),
        ),
    ]
